# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\genius\Desktop\projects\project1\style.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color:white;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignVCenter)
        self.spinBox = QtWidgets.QSpinBox(self.page)
        self.spinBox.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(99999)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignVCenter)
        self.spinBox_2 = QtWidgets.QSpinBox(self.page)
        self.spinBox_2.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_2.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(99999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    border-radius:20px;\n"
"    background-color:#FFFACD;\n"
"    border-color:black;    \n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#FFFAAA;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:#FFE4B5;\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"margin-bottom: 20px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.spinBox_3 = QtWidgets.QSpinBox(self.page_2)
        self.spinBox_3.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_3.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(99999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_3.addWidget(self.spinBox_3, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    border-radius:20px;\n"
"    background-color:#FFFACD;\n"
"    border-color:black;    \n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#FFFAAA;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:#FFE4B5;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    border-radius:20px;\n"
"    background-color:#FFFACD;\n"
"    border-color:black;    \n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#FFFAAA;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:#FFE4B5;\n"
"}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Игра \"Угадай число\" by Dmitr.Pod."))
        self.label.setText(_translate("MainWindow", "Выберите диапазон генерации числа"))
        self.label_2.setText(_translate("MainWindow", "От"))
        self.label_3.setText(_translate("MainWindow", "до"))
        self.pushButton.setText(_translate("MainWindow", "Начать"))
        self.label_4.setText(_translate("MainWindow", "Введите предполагаемое число"))
        self.pushButton_2.setText(_translate("MainWindow", "Далее"))
        self.pushButton_3.setText(_translate("MainWindow", "Назад"))

        def clickNext():
                Range_1 = self.spinBox.value()
                Range_2 = self.spinBox_2.value()
                global Number
                global Check_Win
                Check_Win = 0
                self.label_5.setText("")
                self.pushButton_2.setText("Далее")
                self.stackedWidget.setCurrentWidget(ui.page_2)
                Number = random.randint(Range_1, Range_2)

        
        def clickAnswer():
             Maybe_Answer = self.spinBox_3.value()
             global Check_Win
             if Check_Win == 1:
                self.stackedWidget.setCurrentWidget(ui.page)
             if Maybe_Answer > Number:
                self.label_5.setText("Меньше!")
             elif Maybe_Answer < Number:
                self.label_5.setText("Больше!")
             elif Maybe_Answer == Number:
                self.label_5.setText(f"Поздравляю, вы победили!\nПравильное число {Maybe_Answer}")
                Check_Win = 1
             if Check_Win == 1:
                self.pushButton_2.setText("Начать заново")

        def BackMain():
            self.stackedWidget.setCurrentWidget(ui.page)

        


        
        self.pushButton.clicked.connect(clickNext)
        self.pushButton_2.clicked.connect(clickAnswer)
        self.pushButton_3.clicked.connect(BackMain)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
